### ISSUE TITLE
Define audit output based on audit

### ISSUE THREAD

**Issue by thatch45** [HubbleStack/Nova#245]
Right now when we get the return data from hubble and we run multiple audits, all of the audit's return data is squished together, would it work to change the return structure to be more like this:

```
cve.scan-v2:
  Failure:
    ...
  Sucess:
    ...
cis.scan...:
  Failure:
...
```

Thanks!

**Comment by basepi** [comment]
It could work, theoretically. We've talked about it internally.

The biggest problem is generality. I tried to keep the return structure as boring and simple as possible. This allows us to do things like compliance percentages very easily. But we did discover that we wanted to know from which profile a check originated. So we added `show_profile` as an argument to hubble.audit and hubble.top, so that in verbose mode the profile would be included in the data for each audit.

This works well for us because we treat each audit result as a separate piece of data in splunk.

We would probably implement this via a pretty basic transformation of the data. With `show_profile=True`, we have all the data we need to format the return grouped by profile. And if we use another argument or configuration value then it maintains backward compatibility.

So I'm going to mark this as "sure, we can do this at some point" but it won't be a priority. In the meantime, if you just set `verbose=True, show_profile=True`, then you could easily implement this transformation in post-processing.

**Comment by thatch45** [comment]
That should solve my problem, sorry to use your issue tracker for what turned out to be an expression of my RTFM!

**Comment by basepi** [comment]
Hahaha, no worries. :)
